<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>321a3a19-fa91-44f3-90b2-ea5ba41c6b53</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Controllers\UserController.cs~RF19c2b06a.TMP" />
    <None Remove="Data\ApplicationDbContext.cs~RF11b912d8.TMP" />
    <None Remove="Enums\OrderStatus.cs~RF11fbfa49.TMP" />
    <None Remove="Extensions\DatabaseExtensions.cs~RF11caeba1.TMP" />
    <None Remove="Models\Order.cs~RF121a645b.TMP" />
    <None Remove="Models\Order.cs~RFf10ec6f.TMP" />
    <None Remove="Models\Order.cs~RFf348c4f.TMP" />
    <None Remove="Models\OrderItem.cs~RFf13416b.TMP" />
    <None Remove="Models\Review.cs~RFf14ebc0.TMP" />
    <None Remove="Models\SneakerImages.cs~RF12086ccf.TMP" />
    <None Remove="Services\IUserService.cs~RF198be1d6.TMP" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\Dashboard\" />
    <Folder Include="Views\Cart\" />
    <Folder Include="Views\User\" />
    <Folder Include="Views\Order\" />
    <Folder Include="Views\Sneaker\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CloudinaryDotNet" Version="1.29.2" />
    <PackageReference Include="MySqlConnector" Version="2.6.1" />
  </ItemGroup>

</Project>
